# Generated by Django 4.1.4 on 2023-01-06 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, unique=True)),
                ('number_of_songs', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.CharField(max_length=50)),
                ('artist', models.CharField(max_length=50, unique=True)),
                ('album', models.CharField(max_length=70)),
                ('length', models.TimeField()),
                ('playlist_name', models.ManyToManyField(to='zing_it.playlist')),
            ],
        ),
    ]
